services:
  - type: web
    name: gala-seating
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --worker-class gevent -w 1 app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.4
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: gala-seating-db
          property: connectionString

databases:
  - name: gala-seating-db
    databaseName: gala_seating
    user: gala_user
